// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Banco descartável que o `migrate dev` / `migrate diff` usa para calcular o
    // SQL de uma migration nova. Sem isto, o Prisma CRIA E DERRUBA um banco
    // temporário no MESMO servidor de `DATABASE_URL` — se o .env estiver
    // apontando para produção, é DDL em produção só por gerar migration.
    //
    // Ausente (o caso do Railway, que só roda `migrate deploy`), fica
    // `undefined` e nada muda: deploy não usa shadow.
    //
    // Local: SHADOW_DATABASE_URL=postgresql://.../cockpit_shadow no .env.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
